//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordClasses
{
    using System;
    using System.Collections.Generic;
    using System.Windows;
    using System.Windows.Controls;
    using System.Windows.Media;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientService = new HashSet<ClientService>();
            this.ServicePhoto = new HashSet<ServicePhoto>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public int DurationInSeconds { get; set; }
        public string Description { get; set; }
        public Nullable<double> Discount { get; set; }
        public string MainImagePath { get; set; }

        public string DisplayDuration
        {
            get
            {
                return $"рублей за {DurationInSeconds} минут";
            }
        }

        public string DisplayDiscount
        {
            get
            {
                if (Discount != null)
                {
                    return $"* скидка {Discount * 100}%";
                }
                else
                {
                    return "";
                }
            }
        }

        public TextDecorationCollection textBlock
        {
            get
            {
               if (Discount != null)
               {
                    return TextDecorations.Strikethrough;
               }
               else
               {
                    return null;
               }
            }
        }

        public string DisplayImage
        {
            get
            {
                if (MainImagePath == null)
                {
                    return null;
                }
                if (MainImagePath.Contains("C:\\"))
                {
                    return MainImagePath;
                }
                else
                {
                    return $"/Pic/{MainImagePath.Trim()}";
                }

            }
        }

        public string CostWithDiscount
        {
            get
            {
                if (Discount != null)
                {
                    return (Cost - (Cost * decimal.Parse(Discount.ToString()))).ToString("F2");
                }
                else
                {
                    return "";
                }
            }
        }

        public decimal ResultPrice
        {
            get
            {
                if (Discount != null)
                {
                    return (Cost - (Cost * decimal.Parse(Discount.ToString())));
                }
                else
                {
                    return Cost;
                }
            }
        }

        public SolidColorBrush DiscountColor
        {
            get
            {
                if (Discount > 0)
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFrom("#eaf9c5");
                }
                else
                {
                    return Brushes.LightGray;
                }
            }
        }
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhoto { get; set; }
    }
}
